---
# tasks file for postgresql

- name: Disable RHEL8 Postgres module
  command: dnf -y module disable postgresql

- name: Install Postgres packages
  dnf:
    name: "{{ package }}"
    state: present
    disable_gpg_check: true
  loop:
    - "{{ postgres_rhel8_repo }}"
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: package

- name: Check if Postgres initialized
  stat:
    path: "{{ postgres_12_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- when: not r_postgres_init_dir_state.stat.exists
  name: Run Postgres initdb to initialize if postgres not initialized
  command: "{{ postgres_12_bin_path }}/postgresql-12-setup initdb"
  notify: restart_postgres

- name: Setup Postgres for remote password auth
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_12_data_dir }}/pg_hba.conf"
  notify: restart_postgres

- name: Setup Postgres to listen on network interfaces
  lineinfile:
    dest: "{{ postgres_12_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart_postgres

- name: Setup Postgres as started and enabled on boot.
  service:
    name: "{{ postgres_service }}"
    state: "{{ postgres_service_state | default('started') }}"
    enabled: "{{ postgres_service_enabled | default(true) }}"

- name: Configure Postgres resources, user, database etc
  block:

    - name: Setup Postgres database(s)
      postgresql_db:
        name: "{{ database.name }}"
        state: "{{ database.state | default('present') }}"
      loop: "{{ postgres_databases }}"
      loop_control:
        loop_var: database

    - name: Create Postgres user#(s)
      postgresql_user:
        name: "{{ user.name }}"
        password: "{{ user.password | default(omit) }}"
        encrypted: true
        priv: "{{ user.priv | default(omit) }}"
        db: "{{ user.database | default(omit) }}"
        state: "{{ user.state | default('present') }}"
      loop: "{{ postgres_users }}"
      loop_control:
        loop_var: user
      no_log: "{{ postgres_user_no_log_state | default(false) }}"

  become_user: "{{ postgres_user }}"
