
---
- name: Provision Openstack servers
  hosts: localhost

  vars:
    GUID: "{{ lookup('env', 'GUID') | default(omit) }}"

  tasks:
    - name: Get control node facts from Openstack
      os_server_info:
        cloud: "{{ instance_cloud | default(omit) }}"
        server: control
      register: control_node_info

#     - name: Show all gathered info
#       debug:
#         msg: "{{ control_node_info }}"

    - name: Control node internal ip, as DNS server
      debug:
        msg: "{{ control_node_info.openstack_servers[0].private_v4 }}"

    - name: "Create the OpenStack instances"
      include_role:
        name: openstack_instances
      vars:
        openstack_instances:

# Load Balancer Instance

          - name: dev-lb
            dns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
            metadata: "AnsibleGroup=load_balancers,deployment_name=dev"

# Database Instance

          - name: dev-db
            dns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
            metadata: "AnsibleGroup=database_servers,deployment_name=dev"

# App Instances

          - name: dev-app1
            dns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
            metadata: "AnsibleGroup=app_servers,deployment_name=dev"

          - name: dev-app2
            dns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
            metadata: "AnsibleGroup=app_servers,deployment_name=dev"

