---
- name: Inventory time
  hosts: localhost
  gather_facts: false
  #vars_files:
  #  - vars/main-vars.yml
  tasks:
    - name: Instances info
      os_server_info:
        server: dev-*
      register: dev_instances_info

    - name: Instances to inventory
      add_host:
        host: "{{ instance.name }}"
        group: "{{ instance.metadata.AnsibleGroup }}"
        ansible_host: "{{ instance.private_v4 }}"
      loop: "{{ dev_instances_info.openstack_servers }}"
      loop_control:
        loop_var: instance
